[package]
name = "memoized"
version = "0.1.0"
authors = ["zitudu <zitudu@protonmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
